import crypto from 'node:crypto';
import pg from 'pg';
import { appendAuditInTransaction, emptyAuditState, ensureAuditTables, readAuditState, seedAuditState } from '../src/postgres-audit-v2.mjs';
import { acquireIdempotencyLock, ensureIdempotencyTable, readIdempotencyResult, storeIdempotencyResult } from '../src/postgres-idempotency-v2-1.mjs';
import { ensureDocumentTables, exportDocumentSnapshot, findDocumentById, insertDocumentIfAbsent, migrateLegacyDocuments, putBlob, readDocuments, restoreDocumentSnapshot, validateDocumentSnapshot } from '../src/postgres-documents-v3.mjs';
import { verifyAudit } from '../src/audit-integrity-v1-6.mjs';
const url=process.env.CJ_DATABASE_URL;if(!url)throw new Error('CJ_DATABASE_URL ausente.');
const pool=new pg.Pool({connectionString:url,max:40}),phases=[];const phase=(name,ok,extra={})=>{phases.push({name,ok,...extra});if(!ok)throw new Error(`Gate falhou: ${name}`);};
const idemSecret=crypto.randomBytes(32),auditKey=crypto.randomBytes(32),ring={activeKeyId:'document-audit',legacyKeyId:'document-audit',source:'ci',keys:new Map([['document-audit',auditKey]])};const startedAt=new Date().toISOString(),now=()=>new Date().toISOString(),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const make=(id,processId=`proc-${id}`,text=`payload-${id}`)=>{const bytes=Buffer.from(text),h=hash(bytes);return{bytes,document:{id,processId,name:`${id}.pdf`,mimeType:'application/pdf',size:bytes.length,sha256:h,storedSha256:h,storageBackend:'postgres',encryptionKeyId:'doc-ci',createdAt:now()}}};
const audit=(id,entityId)=>({id,action:'UPLOAD',entity:'document',entityId,requestId:id,actor:{id:'u-ci',role:'admin'},detail:{gate:'v3.0'},at:now()});
async function createDocument(item,key,auditId=`audit-${item.document.id}`){const c=await pool.connect();try{await c.query('BEGIN');let idem=null;if(key){idem=await acquireIdempotencyLock(c,'document',key,idemSecret);const replay=await readIdempotencyResult(c,idem.scope,idem.keyHash);if(replay!==null){await c.query('COMMIT');return{...replay,replayed:true};}}const inserted=await insertDocumentIfAbsent(c,item.document);let out;if(!inserted.inserted)out={document:inserted.document,duplicate:true};else{await putBlob(c,item.document.id,item.bytes,item.document.storedSha256);await appendAuditInTransaction(c,audit(auditId,item.document.id),ring);out={document:item.document};}if(idem)await storeIdempotencyResult(c,idem.scope,idem.keyHash,out);await c.query('COMMIT');return out;}catch(e){try{await c.query('ROLLBACK')}catch{}throw e}finally{c.release();}}
async function withStateLocked(work,timeoutMs=7000){const c=await pool.connect();let timer;try{await c.query('BEGIN');await c.query('SELECT state FROM central_juridica_state WHERE singleton=TRUE FOR UPDATE');return await Promise.race([Promise.resolve().then(work),new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(`STATE_LOCK_INDEPENDENCE_TIMEOUT_${timeoutMs}`)),timeoutMs);})]);}finally{if(timer)clearTimeout(timer);try{await c.query('ROLLBACK')}catch{}c.release();}}
try{
 const version=await pool.query('select version() as version');phase('postgres-connectivity',true,{version:version.rows[0].version});
 await pool.query(`CREATE TABLE IF NOT EXISTS central_juridica_state(singleton boolean PRIMARY KEY DEFAULT TRUE CHECK(singleton=TRUE),state jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now())`);await pool.query('DELETE FROM central_juridica_state');
 await ensureAuditTables(pool);await pool.query('DELETE FROM central_juridica_audit_log');await pool.query('DELETE FROM central_juridica_audit_meta');await seedAuditState(pool,emptyAuditState(ring),ring);await ensureIdempotencyTable(pool);await pool.query('DELETE FROM central_juridica_idempotency');await ensureDocumentTables(pool);await pool.query('DELETE FROM central_juridica_document_blobs');await pool.query('DELETE FROM central_juridica_documents');
 const legacy=make('legacy-doc','legacy-proc','legacy-content');await pool.query('INSERT INTO central_juridica_state(singleton,state) VALUES(TRUE,$1::jsonb)',[JSON.stringify({documents:[legacy.document]})]);const mig=await migrateLegacyDocuments(pool);phase('legacy-document-metadata-migrated',mig.migrated===1);const physical=(await pool.query('SELECT state FROM central_juridica_state WHERE singleton=TRUE')).rows[0].state;phase('document-metadata-outside-jsonb',Array.isArray(physical.documents)&&physical.documents.length===0&&Boolean(await findDocumentById(pool,'legacy-doc')));await putBlob(pool,legacy.document.id,legacy.bytes,legacy.document.storedSha256);
 const independent=make('independent-doc','proc-independent','independent-content');const independentResult=await withStateLocked(()=>createDocument(independent,null));phase('document-create-without-key-outside-state-lock',independentResult.document?.id===independent.document.id);const independentRows=await pool.query("SELECT count(*)::int n FROM central_juridica_document_blobs WHERE document_id='independent-doc'");phase('metadata-blob-audit-atomic-create',Number(independentRows.rows[0].n)===1&&Number((await pool.query("SELECT count(*)::int n FROM central_juridica_audit_log WHERE payload->>'entityId'='independent-doc'")).rows[0].n)===1);
 const same=make('same-doc','proc-same','same-content'),writes=25,results=await Promise.all(Array.from({length:writes},()=>createDocument(same,'same-doc-key')));const metaRows=Number((await pool.query("SELECT count(*)::int n FROM central_juridica_documents WHERE document_id='same-doc'")).rows[0].n),blobRows=Number((await pool.query("SELECT count(*)::int n FROM central_juridica_document_blobs WHERE document_id='same-doc'")).rows[0].n),replayed=results.filter(r=>r.replayed).length,auditRows=Number((await pool.query("SELECT count(*)::int n FROM central_juridica_audit_log WHERE payload->>'entityId'='same-doc'")).rows[0].n);phase('document-idempotent-concurrency',metaRows===1&&blobRows===1&&replayed===24&&auditRows===1,{writers:writes,metadataRows:metaRows,blobRows,replayed,auditRows,duplicateCreates:metaRows-1});
 await withStateLocked(()=>Promise.all(Array.from({length:25},(_,i)=>createDocument(make(`parallel-doc-${i}`,`proc-parallel-${i}`,`parallel-${i}`),`parallel-doc-key-${i}`))),12000);phase('parallel-document-writes-outside-state-lock',true,{writers:25});
 const beforeAudit=(await readAuditState(pool)).auditLog.length,beforeMeta=Number((await pool.query('SELECT count(*)::int n FROM central_juridica_documents')).rows[0].n),beforeBlobs=Number((await pool.query('SELECT count(*)::int n FROM central_juridica_document_blobs')).rows[0].n);const duplicate=make('same-doc-other-id','proc-same','same-content');const dup=await createDocument(duplicate,'different-key');const afterAudit=(await readAuditState(pool)).auditLog.length;phase('process-hash-dedup-no-extra-blob-or-audit',dup.duplicate===true&&dup.document.id==='same-doc'&&Number((await pool.query('SELECT count(*)::int n FROM central_juridica_documents')).rows[0].n)===beforeMeta&&Number((await pool.query('SELECT count(*)::int n FROM central_juridica_document_blobs')).rows[0].n)===beforeBlobs&&afterAudit===beforeAudit);
 const failItem=make('rollback-doc','proc-rollback','rollback-content');let failed=false;try{await createDocument(failItem,'rollback-key','audit-independent-doc');}catch{failed=true;}phase('document-rollback-includes-metadata-blob-audit',failed&&!await findDocumentById(pool,'rollback-doc')&&Number((await pool.query("SELECT count(*)::int n FROM central_juridica_document_blobs WHERE document_id='rollback-doc'")).rows[0].n)===0&&verifyAudit(await readAuditState(pool),ring).ok===true);
 const snapshot=await exportDocumentSnapshot(pool);validateDocumentSnapshot(snapshot);const originalMeta=snapshot.metadata.length,originalBlobs=snapshot.blobs.length;const c=await pool.connect();try{await c.query('BEGIN');await restoreDocumentSnapshot(c,snapshot);await c.query('COMMIT');}catch(e){try{await c.query('ROLLBACK')}catch{}throw e}finally{c.release();}const restored=await exportDocumentSnapshot(pool);phase('document-snapshot-restore-1to1',restored.metadata.length===originalMeta&&restored.blobs.length===originalBlobs&&restored.metadata.length===restored.blobs.length,{metadata:restored.metadata.length,blobs:restored.blobs.length});
 let orphan=false,missing=false;try{validateDocumentSnapshot({metadata:[],blobs:[snapshot.blobs[0]]});}catch(e){orphan=/ORPHAN_BLOB/.test(e.message);}try{validateDocumentSnapshot({metadata:[snapshot.metadata[0]],blobs:[]});}catch(e){missing=/MISSING_BLOB/.test(e.message);}phase('inconsistent-document-snapshot-fails-closed',orphan&&missing,{orphanRejected:orphan,missingBlobRejected:missing});
 const stored=(await pool.query("SELECT stored_sha256,payload FROM central_juridica_document_blobs WHERE document_id='same-doc'")).rows[0];phase('stored-document-hash-exact',stored.stored_sha256===hash(stored.payload),{storedSha256:stored.stored_sha256});
 const total=(await readDocuments(pool)).length;const summary={dedicatedDocumentMetadataTable:true,documentMetadataOutsideJsonb:true,blobMetadataAuditAtomicity:true,noKeyCreateOutsideStateLock:true,idempotentConcurrentRequests:25,idempotentDocumentCreates:1,idempotentReplays:24,parallelDocumentWriters:25,processHashDedup:true,rollbackAtomicity:true,snapshotRestoreOneToOne:true,inconsistentSnapshotFailClosed:true,storedHashExact:true,totalDocuments:total};console.log(JSON.stringify({ok:true,evidence:{runId:crypto.randomUUID(),startedAt,phases,finishedAt:new Date().toISOString(),summary}},null,2));
}catch(error){console.error(JSON.stringify({ok:false,evidence:{startedAt,phases},error:{name:error.name,message:error.message,stack:error.stack}},null,2));process.exitCode=1;}finally{await pool.end();}
