import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';

const MAGIC=Buffer.from('CJBAK2');
function canonical(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;const k=Object.keys(v).sort();return`{${k.map(x=>`${JSON.stringify(x)}:${canonical(v[x])}`).join(',')}}`;}
function derive(master,purpose){return Buffer.from(crypto.hkdfSync('sha256',master,Buffer.from('central-juridica-backup-v2'),Buffer.from(purpose),32));}
function enc(plain,master,aad){const key=derive(master,'payload-encryption');const iv=crypto.randomBytes(12);const c=crypto.createCipheriv('aes-256-gcm',key,iv);c.setAAD(Buffer.from(aad));const ct=Buffer.concat([c.update(Buffer.from(plain)),c.final()]);return Buffer.concat([MAGIC,iv,c.getAuthTag(),ct]);}
function dec(payload,master,aad){const b=Buffer.from(payload);if(!b.subarray(0,MAGIC.length).equals(MAGIC))throw new Error('Envelope inválido.');const key=derive(master,'payload-encryption');const iv=b.subarray(MAGIC.length,MAGIC.length+12);const tag=b.subarray(MAGIC.length+12,MAGIC.length+28);const ct=b.subarray(MAGIC.length+28);const d=crypto.createDecipheriv('aes-256-gcm',key,iv);d.setAAD(Buffer.from(aad));d.setAuthTag(tag);return Buffer.concat([d.update(ct),d.final()]);}
function mac(manifest,master){const copy=structuredClone(manifest);delete copy.manifestMac;return crypto.createHmac('sha256',derive(master,'manifest-authentication')).update(canonical(copy)).digest('hex');}
const hex=b=>crypto.createHash('sha256').update(b).digest('hex');
export async function createSecureBackup({store,backupRoot,backupKey}){const stamp=Date.now().toString(36);const target=path.join(backupRoot,`cj-${stamp}`);await fs.mkdir(path.join(target,'documents'),{recursive:true});const snap=await store.exportSnapshot();const statePlain=Buffer.from(JSON.stringify(snap.state));const stateCipher=enc(statePlain,backupKey,'state.enc');await fs.writeFile(path.join(target,'state.enc'),stateCipher);const documents=[];for(const b of snap.blobs){const name=`documents/${crypto.createHash('sha256').update(b.documentId).digest('hex')}.enc`;const cipher=enc(b.payload,backupKey,name);await fs.writeFile(path.join(target,name),cipher);documents.push({documentId:b.documentId,path:name,cipherSha256:hex(cipher),storedSha256:b.storedSha256});}const manifest={version:2,createdAt:new Date().toISOString(),state:{path:'state.enc',cipherSha256:hex(stateCipher),plainSha256:hex(statePlain)},documents,auditCheckpoint:{headHash:snap.state.auditMeta?.headHash||null,metaMac:snap.state.auditMeta?.metaMac||null,totalAppended:Number(snap.state.auditMeta?.totalAppended||0)}};manifest.manifestMac=mac(manifest,backupKey);await fs.writeFile(path.join(target,'manifest.json'),JSON.stringify(manifest));return{target,manifest};}
export async function verifySecureBackup(target,backupKey){const manifest=JSON.parse(await fs.readFile(path.join(target,'manifest.json'),'utf8'));const errors=[];if(manifest.manifestMac!==mac(manifest,backupKey))errors.push('MANIFEST_MAC_MISMATCH');let state=null;const blobs=[];try{const c=await fs.readFile(path.join(target,manifest.state.path));if(hex(c)!==manifest.state.cipherSha256)errors.push('STATE_CIPHER_HASH_MISMATCH');const p=dec(c,backupKey,manifest.state.path);if(hex(p)!==manifest.state.plainSha256)errors.push('STATE_PLAIN_HASH_MISMATCH');state=JSON.parse(p.toString());}catch{errors.push('STATE_DECRYPT_FAILED');}for(const x of manifest.documents||[]){try{const c=await fs.readFile(path.join(target,x.path));if(hex(c)!==x.cipherSha256)errors.push(`DOC_CIPHER_HASH_MISMATCH:${x.documentId}`);const p=dec(c,backupKey,x.path);if(hex(p)!==x.storedSha256)errors.push(`DOC_STORED_HASH_MISMATCH:${x.documentId}`);blobs.push({documentId:x.documentId,payload:p,storedSha256:x.storedSha256});}catch{errors.push(`DOC_DECRYPT_FAILED:${x.documentId}`);}}if(state){const cp=manifest.auditCheckpoint||{};if((state.auditMeta?.headHash||null)!==(cp.headHash||null))errors.push('AUDIT_HEAD_MISMATCH');if((state.auditMeta?.metaMac||null)!==(cp.metaMac||null))errors.push('AUDIT_META_MAC_MISMATCH');}return{ok:errors.length===0,manifest,state,blobs,errors};}
export async function restoreSecureBackup({store,target,backupKey}){const v=await verifySecureBackup(target,backupKey);if(!v.ok)throw new Error(`Backup seguro inválido: ${v.errors.join(',')}`);return store.restoreSnapshot({state:v.state,blobs:v.blobs});}
